### PR TITLE
Added xxh-config.fish rc file to source plugins.

### PR DESCRIPTION
**Pull request by frederickjh**
Work on #4 to add rc file for loading plugins.

### CODE REVIEW

**Comment by anki-code** [comment]
Good start! I've tested it and it works for sample plugin.

I've created the repo [xxh-plugin-fish-ohmyfish](https://github.com/xxh/xxh-plugin-fish-ohmyfish). Could you create xxh-plugin for [Oh My Fish](https://github.com/oh-my-fish/oh-my-fish) to proof the solution?

**Comment by anki-code** [comment]
@frederickjh please look on this comment - https://github.com/fish-shell/fish-shell/issues/6829#issuecomment-605661229

I think you can replace:
```
$fish_bin $XXH_HOME/.xxh/shells/xxh-shell-fish/build/xxh-config.fish
$fish_bin "${EXECUTE_COMMAND[@]}"  # $EXECUTE_FILE
```
To:
```
$fish_bin -i -C "source $XXH_HOME/.xxh/shells/xxh-shell-fish/build/xxh-config.fish" "${EXECUTE_COMMAND[@]}"  # $EXECUTE_FILE
```
It is more naturally simulate the "rc file pre execution".

**Comment by frederickjh** [comment]
I replaced those two lines of code with one and tested, however to make it easier for those later reading the code I used the long options.

**Comment by frederickjh** [comment]
> I've created the repo [xxh-plugin-fish-ohmyfish](https://github.com/xxh/xxh-plugin-fish-ohmyfish). Could you create xxh-plugin for [Oh My Fish](https://github.com/oh-my-fish/oh-my-fish) to proof the solution?

Maybe later, I am more interested to get a plugin working for [Fisher](https://github.com/jorgebucaran/fisher) another package manager for the Fish Shell, so that I can get this to a usable state for me.

**Comment by anki-code** [comment]
> Fisher 

Created: https://github.com/xxh/xxh-plugin-fish-fisher :)

**Pull request merged**
